version: '3'

services:
  mikutter:
    image: mikutter:mikutter-dev
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mikutter
    command: "/usr/local/bin/ruby mikutter/mikutter.rb --debug"
    stdin_open: true
    tty: true
    environment:
    - "LC_ALL=en_US.UTF-8"

